=== Vinpasso/GamXam/game/questions.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        targetNamespace="https://vpt1.org"
        xmlns="https://vpt1.org"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
    <xs:element name="exam">
        <xs:complexType>
            <xs:all>
                <xs:element name="head">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="version" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="question" type="question" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="question">
        <xs:sequence>
            <xs:element name="body" type="xs:string"/>
            <xs:element name="answers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="answer" type="answer" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="type" type="answer-type" default="all"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="question-type" use="required"/>
    </xs:complexType>

    <xs:complexType name="answer">
        <xs:sequence>
            <xs:element name="body" type="xs:string"/>
            <xs:element name="marks">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mark" type="mark" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="mark">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="keyword"/>
                            <xs:enumeration value="manual"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="points" type="xs:positiveInteger" default="1"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="question-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="extended-answer"/>
            <xs:enumeration value="multiple-choice"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="answer-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="all"/>
            <xs:enumeration value="any"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Vinpasso/GamXam/data/test_questions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<exam xmlns="https://vpt1.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://vpt1.org questions.xsd">
    <head>
        <title>Test Question Catalog</title>
        <version>1.0</version>
        <id>1337</id>
    </head>
    <body>
        <question type="extended-answer" id="0">
            <body>Reg-Ex Test Question: What is the meaning of life? (Answers: 42, fourty-two)</body>
            <answers>
                <answer>
                    <body>42</body>
                    <marks>
                        <mark type="regex">
                            42|fourty[\s-]two
                        </mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="1">
            <body>Keyword Question: What is the name of your university?</body>
            <answers>
                <answer>
                    <body>Technische Universit채t M체nchen</body>
                    <marks>
                        <mark type="keyword" points="1">
                            technische
                        </mark>
                        <mark type="keyword" points="1">
                            universit채t
                        </mark>
                        <mark type="keyword" points="1">
                            m체nchen
                        </mark>
                    </marks>
                </answer>
            </answers>
        </question>
    </body>
</exam>

=== Vinpasso/GamXam/data/pp_questions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<exam xmlns="https://vpt1.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://vpt1.org questions.xsd">
    <head>
        <title>Parallel Programming</title>
        <version>1.0</version>
        <id>161</id>
    </head>
    <body>
        <!-- TODO: Insert questions -->
        <!-- Lecture 2: Threading Concepts Threading APIs POSIX Threads -->
        <question type="extended-answer" id="1">
            <body>What are the four elements of Flynn's taxonomy?</body>
            <answers>
                <answer>
                    <body>SISD (Conventional processor), SIMD (Single instruction multiple data, vectorization, GPU,
                        etc.), MISD (not really available), MIMD (Multiple instruction multiple data,
                        multi-core/processor etc.)
                    </body>
                    <marks>
                        <mark type="keyword">sisd</mark>
                        <mark type="keyword">simd</mark>
                        <mark type="keyword">misd</mark>
                        <mark type="keyword">mimd</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="2">
            <body>What two major types of MIMD architectures exist?</body>
            <answers>
                <answer>
                    <body>Distributed memory and shared memory</body>
                    <marks>
                        <mark type="keyword">distrib</mark>
                        <mark type="keyword">share</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="3">
            <body>What type of distributed memory systems exist and what do they do?</body>
            <answers>
                <answer>
                    <body>MPP, NOW, Cluster (What do they do? TODO)</body>
                    <marks>
                        <mark type="keyword">mpp</mark>
                        <mark type="keyword">now</mark>
                        <mark type="keyword">clust</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="4">
            <body>What are the types and subtypes of shared memory systems?</body>
            <answers>
                <answer>
                    <body>UMA and NUMA (COMA, ccNUMA, nccNUMA)</body>
                    <marks>
                        <mark type="keyword">UMA</mark>
                        <mark type="keyword">NUMA</mark>
                        <mark type="keyword">COMA</mark>
                        <mark type="keyword">cc</mark>
                        <mark type="keyword">ncc</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="5">
            <body>What is another name for the UMA Architecture? What is the defining feature of a UMA system?</body>
            <answers>
                <answer>
                    <body>SMP: Symmetric multiprocessors. There is a centralized shared memory, to which all processors
                        have the same latency.
                    </body>
                    <marks>
                        <mark type="keyword">smp</mark>
                        <mark type="keyword">shared</mark>
                        <mark type="keyword">latenc</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="6">
            <body>What are some programming models that match shared memory?</body>
            <answers>
                <answer>
                    <body>
                        POSIX threads, OpenMP, etc.
                    </body>
                    <marks>
                        <mark type="keyword">posix</mark>
                        <mark type="regex">o(pen)?mp</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="7">
            <body>What is a thread and what are its essential components?</body>
            <answers>
                <answer>
                    <body>An independent stream of execution that has at least its own PC and its own stack.</body>
                    <marks>
                        <mark type="keyword">exec</mark>
                        <mark type="keyword">pc</mark>
                        <mark type="keyword">stack</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="8">
            <body>What is Hyperthreading/SMT?</body>
            <answers>
                <answer>
                    <body>A technology where a processing core can have multiple hardware threads to allow for rapid
                        context switching in the core, reducing the impact of stalls.
                    </body>
                    <marks>
                        <mark type="keyword">thread</mark>
                        <mark type="keyword">switch</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="9">
            <body>What are some advantages of using threads versus multiple processes.</body>
            <answers>
                <answer>
                    <body>
                        No data protection boundaries, asynchronous behavior within a process, OS still does scheduling
                        (preemption and progress)
                    </body>
                    <marks>
                        <mark type="keyword">protect</mark>
                        <mark type="keyword">async</mark>
                        <mark type="keyword">schedul</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="10">
            <body>What is an advantage of using threads (e.g. pthreads) in parallel programming?</body>
            <answers>
                <answer>
                    <body>Its low-level, allowing the programmer to micro-manage resources.</body>
                    <marks>
                        <mark type="keyword">low</mark>
                        <mark type="keyword">resource</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="11">
            <body>What model does pthreads conform to?</body>
            <answers>
                <answer>
                    <body>The fork/join model</body>
                    <marks>
                        <mark type="keyword">fork</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="12">
            <body>Write code to create/destroy a pthread.</body>
            <answers>
                <answer>
                    <body>
                        Using a kernel:
                        <pre>void* kernel(void* arg);</pre>
                        Start a thread:
                        <pre>
                            pthread_t thread;
                            pthread_attr_t attr;
                            if(!pthread_create(&amp;thread, attr, kernel, arg)) {
                                abort(0);
                            }
                        </pre>
                        Join a thread:
                        <pre>
                            if(!pthread_join(&amp;thread, &amp;retval)) {
                                abort(0);
                            }
                        </pre>
                    </body>
                    <marks>
                        <mark type="keyword">create</mark>
                        <mark type="keyword">join</mark>
                    </marks>
                </answer>
            </answers>
        </question>
    </body>
</exam>

=== Vinpasso/GamXam/data/acn_questions.xml
<?xml version="1.0" encoding="UTF-8" ?>

<exam xmlns="https://vpt1.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vpt1.org questions.xsd">
    <head>
        <title>Question Catalog: Advanced Computer Networks</title>
        <version>1.0</version>
        <id>991</id>
    </head>
    <body>
        <!-- Tutorial 1: Qualitative Questions -->
        <question type="extended-answer" id="0">
            <body>What is the major difference between an Internet application and a normal application such as
                Microsoft Word?
            </body>
            <answers>
                <answer>
                    <body>The Internet application is distributed.</body>
                    <marks>
                        <mark type="keyword">distributed</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="1">
            <body>What are the four sources of packet delay?</body>
            <answers>
                <answer>
                    <body>Nodal processing, queueing delay, transmission delay, and propagation delay.</body>
                    <marks>
                        <mark type="keyword">nodal processing</mark>
                        <mark type="keyword">queuing</mark>
                        <mark type="keyword">transmission</mark>
                        <mark type="keyword">propagation</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="2">
            <body>What are the two types of services that the Internet provides to its applications? What are their
                characteristics?
            </body>
            <answers>
                <answer>
                    <body>TCP: connection-oriented service, providers reliable transfer; UDP: connectionless service, no
                        transfer guarantees
                    </body>
                    <marks>
                        <mark type="keyword">TCP</mark>
                        <mark type="keyword">UDP</mark>
                        <mark type="keyword">connection</mark>
                        <mark type="keyword">reliable</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="3">
            <body>What is the most important difference in the circuit switching and packet switching techniques?</body>
            <answers>
                <answer>
                    <body>Circuit switching: dedicated communication path between two stations; Packet switching:
                        resources are dynamically shared on a per-packet basis
                    </body>
                    <marks>
                        <mark type="keyword">dedicated communication path</mark>
                        <mark type="keyword">dynamically shared</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="4">
            <body>What is the main advantage of using a packet switching network?</body>
            <answers>
                <answer>
                    <body>It allows for more efficient use of the network resources.</body>
                    <marks>
                        <mark type="keyword">more efficient</mark>
                    </marks>
                </answer>
            </answers>
        </question>
        <question type="extended-answer" id="5">
            <body>List six different access technologies. Classify each one as residential, company or mobile access.
            </body>
            <answers>
                <answer>
                    <body>Dial-up modem over telephone line: residential; DSL over telephone line: residential (or small
                        office); Cable to HFC: residential; 100Mbps switched Ethernet: company; WLAN: mobile; Cellular
                        mobile access: mobile
                    </body>
                    <marks>
                        <mark type="keyword">dial-up modem</mark>
                        <mark type="keyword">DSL</mark>
                        <mark type="keyword">Cable to HFC</mark>
                        <mark type="keyword">100Mbps switched Ethernet</mark>
                        <mark type="keyword">WLAN</mark>
                        <mark type="keyword">Cellular</mark>
                    </marks>
                </answer>
            </answers>
        </question>
    </body>
</exam>
